import { useEffect, useState } from "react";
import { getModelConfig, getModelStatus, testModel, updateModelConfig, type ProviderHealth } from "../services/api";
import { useI18n } from "../i18n";

export function ProviderSettings({onConfigChange, providerHealth = {}, onHealthChange}:{onConfigChange?:(config:any)=>void; providerHealth?:Record<string, ProviderHealth>; onHealthChange?:(provider:string, health:ProviderHealth)=>void}){
 const { t } = useI18n();
 const [c,setC]=useState<any>(null),[f,setF]=useState<any>({}),[n,setN]=useState(""),[noticeKind,setNoticeKind]=useState<"success"|"error">("error"),[busy,setBusy]=useState("");
 const notify=(message:string,kind:"success"|"error"="error")=>{setN(message);setNoticeKind(kind)};
 useEffect(()=>{void getModelConfig().then(x=>{setC(x);setF({openai_base_url:x.openai?.base_url||"https://api.openai.com/v1",openai_model:x.openai?.model||"",claude_base_url:x.claude?.base_url||"https://api.anthropic.com",claude_model:x.claude?.model||""})}).catch(e=>notify(e instanceof Error?e.message:t("Configuration failed")))},[]);
 const set=(k:string,v:string)=>setF((x:any)=>({...x,[k]:v})); const save=async(provider:"openai"|"claude")=>{setBusy(provider);try{const next=await updateModelConfig({...f,ai_provider:provider});setC(next);onConfigChange?.(next);void getModelStatus(true).then(status=>Object.entries(status.providers||{}).forEach(([name,result])=>onHealthChange?.(name,result))).catch(()=>undefined);notify(`${provider === "openai" ? "OpenAI" : "Claude"} ${t("saved and selected for classification. Secrets are never returned.")}`,"success")}catch(e){notify(e instanceof Error?e.message:t("Save failed"))}finally{setBusy("")}};
 const test=async(p:"openai"|"gemini"|"claude"|"ollama")=>{setBusy(p);try{const x=await testModel(p);onHealthChange?.(p,x);notify(x.ok?`${p} ${t("connected") } · ${x.model}`:(x.error||t("Connection test failed")),x.ok?"success":"error")}catch(e){notify(e instanceof Error?e.message:t("Test failed"))}finally{setBusy("")}};
 const badge=(name:string, fallback:boolean) => providerHealth[name] ? (providerHealth[name].ok ? {label:t("Active"), className:"auto_classified"} : {label:t("Unavailable"), className:"neutral"}) : (fallback ? {label:t("Configured"), className:"neutral"} : {label:t("Not configured"), className:"neutral"});
 const openaiBadge=badge("openai",Boolean(c?.openai?.api_key_configured && c?.openai?.model));
 const claudeBadge=badge("claude",Boolean(c?.claude?.api_key_configured && c?.claude?.model));
 if(!c)return <div className="loading">{t("Provider settings loading…")}</div>;
 return <section className="model-cards provider-settings"><article className="panel model-card"><div className="section-title"><span>OPENAI / CHATGPT</span><h2>{t("OpenAI-compatible API")}</h2><span className={`badge ${openaiBadge.className}`}>{openaiBadge.label}</span></div><div className="model-form"><label>{t("API Key")}<input type="password" placeholder="sk-… (never displayed)" value={f.openai_api_key||""} onChange={e=>set("openai_api_key",e.target.value)}/></label><label>{t("Base URL")}<input value={f.openai_base_url||""} onChange={e=>set("openai_base_url",e.target.value)}/></label><label>{t("Model")}<input placeholder="gpt-4o-mini" value={f.openai_model||""} onChange={e=>set("openai_model",e.target.value)}/></label><p>{t("Saving selects this provider for subsequent classifications.")}</p><div className="review-actions"><button className="primary" onClick={()=>void save("openai")} disabled={!!busy}>{busy==="openai"?t("Saving…"):t("Save & Use for Classification")}</button><button onClick={()=>void test("openai")} disabled={!!busy}>{t("Test Connection")}</button></div></div></article><article className="panel model-card"><div className="section-title"><span>CLAUDE</span><h2>{t("Anthropic Claude API")}</h2><span className={`badge ${claudeBadge.className}`}>{claudeBadge.label}</span></div><div className="model-form"><label>{t("API Key")}<input type="password" placeholder="sk-ant-… (never displayed)" value={f.claude_api_key||""} onChange={e=>set("claude_api_key",e.target.value)}/></label><label>{t("Base URL")}<input value={f.claude_base_url||"https://api.anthropic.com"} onChange={e=>set("f.claude_base_url",e.target.value)}/></label><label>{t("Model")}<input placeholder="claude-3-5-sonnet-latest" value={f.claude_model||""} onChange={e=>set("f.claude_model",e.target.value)}/></label><p>{t("Saving selects this provider for subsequent classifications.")}</p><div className="review-actions"><button className="primary" onClick={()=>void save("claude")} disabled={!!busy}>{busy==="claude"?t("Saving…"):t("Save & Use for Classification")}</button><button onClick={()=>void test("claude")} disabled={!!busy}>{t("Test Connection")}</button></div></div></article>{n&&<div className={noticeKind==="success"?"success-message":"error"} role="status" aria-live="polite">{n}</div>}</section>;
}
