import { Link } from "react-router-dom";

const sections = [
  ["01", "Ingestion", "ET .rules files are loaded. Disabled rules are skipped and SID + REV is stored as an immutable rule record."],
  ["02", "Parser", "The deterministic Suricata parser extracts protocol, addresses, ports, content, PCRE, flow, metadata and app-layer fields."],
  ["03", "Enrichment", "Local, explainable hints identify indicators, candidate entities, CVE references and possible MITRE evidence. Hints are not ground truth."],
  ["04", "Provider", "The selected provider receives a bounded ClassificationContext and returns the strict Pydantic classification schema."],
  ["05", "Validation", "Taxonomy, canonical MITRE relationships, evidence gates and consistency checks validate the proposed output."],
  ["06", "Catalog", "The latest successful classification is exposed through FastAPI and rendered in Rule Explorer, MITRE Catalog and Model Lab."]
] as const;

const tables = [
  ["rules", "One row per SID + REV", "raw_rule, msg, protocol, ports, contents, pcre, app_layer, metadata, source_file"],
  ["classifications", "Every provider output", "final fields, confidence, provider, model, evidence, validation, provenance and timing"],
  ["manual_reviews", "Human review history", "APPROVED, REJECTED or NEEDS_REVIEW; never created automatically by AI"],
  ["classification_runs", "Batch/run provenance", "run_id, provider, model, totals, timestamps and success/failure counts"],
  ["comparison_reviews", "Gemini vs Qwen comparisons", "Two classification IDs, analyst preference and optional note"],
  ["rule_product_decisions", "Product planning", "Candidate, shortlisted, approved or rejected independently of AI review"]
] as const;

export function Documentation() {
  return <div className="docs-page">
    <header className="docs-hero">
      <div className="section-kicker">ENGINEERING HANDBOOK · V2</div>
      <h1>Platform Documentation</h1>
      <p>A precise field guide for engineers, analysts and future frontends integrating the Suricata Detection Catalog.</p>
      <div className="docs-hero-meta"><span>FastAPI + SQLite + React</span><span>Gemini API / local Qwen</span><span>Human-reviewed ground truth only</span></div>
    </header>
    <div className="docs-layout">
      <aside className="docs-toc"><div className="docs-toc-title">CONTENTS</div>
        {["Overview","Architecture","Providers","Database","API contract","Classification states","MITRE & confidence","Operations","Integration rules"].map((x, i) => <a href={`#docs-${i + 1}`} key={x}>{String(i + 1).padStart(2, "0")} {x}</a>)}
        <Link className="docs-back" to="/catalog">← Back to catalog</Link>
      </aside>
      <main className="docs-content">
        <section id="docs-1" className="docs-section"><div className="docs-index">01 / OVERVIEW</div><h2>What this platform does</h2><p>The platform turns a large Emerging Threats Suricata ruleset into an inspectable detection catalogue. It preserves the original signature, makes parser output visible, asks one configured AI provider for a structured classification, validates that result, and stores every stage for later comparison.</p><div className="docs-callout"><strong>Design principle</strong><span>Deterministic evidence is authoritative for structure. AI proposes semantic labels. Validation decides whether the proposal is safe to expose.</span></div><div className="docs-quick-grid"><div><b>Input</b><span>Suricata <code>.rules</code> files</span></div><div><b>Output</b><span>Searchable rule and classification records</span></div><div><b>Users</b><span>Detection engineers, analysts, product owners</span></div><div><b>Review boundary</b><span>AI output never becomes human-approved automatically</span></div></div></section>
        <section id="docs-2" className="docs-section"><div className="docs-index">02 / ARCHITECTURE</div><h2>End-to-end processing line</h2><p>The same pipeline serves the dashboard, batch runner and Model Lab. A frontend does not parse or classify rules itself; it reads the API's canonical representation.</p><div className="docs-pipeline">{sections.map(([n, title, text]) => <div className="docs-pipeline-step" key={n}><b>{n}</b><div><h3>{title}</h3><p>{text}</p></div></div>)}</div><pre className="docs-code">{`ET .rules → RuleLoader → SuricataRuleParser → Enrichment hints
                              ↓
                   ClassificationContext (JSON)
                              ↓
             Gemini generateContent  |  Ollama /api/chat
                              ↓
        Pydantic schema → taxonomy/MITRE validation → SQLite
                              ↓
                         FastAPI → React`}</pre></section>
        <section id="docs-3" className="docs-section"><div className="docs-index">03 / PROVIDERS</div><h2>Gemini and Qwen execution</h2><div className="docs-provider-grid"><article><div className="docs-provider-label gemini">GEMINI · API</div><h3>Remote structured classification</h3><p>Gemini is selected through <code>AI_PROVIDER=gemini</code>. The API key and model are read from environment/runtime settings. The adapter calls Google's <code>generateContent</code> method and requests the same structured Pydantic-compatible JSON schema used by the local provider.</p><ul><li>Requires internet and a valid <code>GEMINI_API_KEY</code>.</li><li>Rate limits use bounded retry/backoff.</li><li>Secrets and prompts are never written to logs.</li></ul></article><article><div className="docs-provider-label qwen">QWEN3 8B · LOCAL</div><h3>Local deterministic inference</h3><p>Qwen runs through Ollama at <code>OLLAMA_BASE_URL</code>, normally <code>http://127.0.0.1:11434</code>. The adapter sends <code>think: false</code>, temperature 0 and a JSON schema to <code>/api/chat</code>. Its output passes through the same V2 hardening, MITRE decision and validator layers.</p><ul><li>After the model is downloaded, basic classification can run offline.</li><li>GPU offload and Ollama keep-alive determine throughput.</li><li>Qwen and Gemini share the same input contract, not the same model.</li></ul></article></div><div className="docs-callout amber"><strong>Provider rule</strong><span>Changing the provider changes only the inference adapter. Parser, taxonomy, database schema, provenance and frontend contract remain shared.</span></div></section>
        <section id="docs-4" className="docs-section"><div className="docs-index">04 / DATABASE</div><h2>SQLite location and data model</h2><p>Local development uses SQLite through SQLAlchemy. The default database is <code>backend/suricata_rules.db</code> (the exact path can be changed with <code>DATABASE_URL</code>). SQLite is a file database and can be inspected with DB Browser for SQLite or any SQLite-compatible client.</p><div className="docs-table-wrap"><table className="docs-table"><thead><tr><th>Table</th><th>Purpose</th><th>Important fields</th></tr></thead><tbody>{tables.map(([name, purpose, fields]) => <tr key={name}><td><code>{name}</code></td><td>{purpose}</td><td>{fields}</td></tr>)}</tbody></table></div><p className="docs-note">Do not edit live rows while a classifier batch is writing. Make a backup first, or use the API for changes that need audit history.</p></section>
        <section id="docs-5" className="docs-section"><div className="docs-index">05 / API CONTRACT</div><h2>Using the data from another frontend</h2><p>Any client can consume the catalogue without importing Python code. The API is the integration boundary.</p><div className="docs-endpoints">{[["GET","/api/rules?limit=50","Paginated catalogue with category, provider, model, MITRE and batch filters."],["GET","/api/rules/{sid}","Full rule detail: raw signature, parsed input, latest classification and review metadata."],["GET","/api/stats","Workspace totals, status counts and distributions."],["POST","/api/rules/{sid}/classify","Classify one rule; successful results are cached unless force=true."],["GET","/api/catalog/facets","Category, tactic, technique and product-planning facets."]].map(([verb,path,desc]) => <div className="docs-endpoint" key={path}><b className={verb === "GET" ? "get" : "post"}>{verb}</b><code>{path}</code><span>{desc}</span></div>)}</div><pre className="docs-code">{`fetch("/api/rules?provider=ollama&model_name=qwen3:8b")
  .then(response => response.json())
  .then(({ items, total }) => renderRules(items, total));`}</pre></section>
        <section id="docs-6" className="docs-section"><div className="docs-index">06 / STATE MODEL</div><h2>Classification, validation and human review</h2><div className="docs-state-grid"><div><b className="state-green">AUTO_CLASSIFIED</b><span>AI result passed normal validation and is available for catalogue use.</span></div><div><b className="state-amber">REVIEW_REQUIRED</b><span>Validator found an issue or insufficient evidence. This is an AI/system state, not human approval.</span></div><div><b className="state-red">FAILED</b><span>Provider or processing failure retained as diagnostic history.</span></div><div><b className="state-blue">UNREVIEWED</b><span>Human review has not been recorded for an existing classification.</span></div></div><p>Manual review states (<code>APPROVED</code>, <code>REJECTED</code>, <code>NEEDS_REVIEW</code>) are created only by an analyst. A rule can be <code>AUTO_CLASSIFIED</code> while individual fields remain <code>ABSTAINED</code>.</p></section>
        <section id="docs-7" className="docs-section"><div className="docs-index">07 / SEMANTICS</div><h2>MITRE provenance and confidence</h2><div className="docs-semantic-grid"><div><h3>MITRE mapping</h3><p><code>source_mitre_mapping</code> records rule metadata. <code>final_mitre_mapping</code> records the validated system decision. <code>mitre_mapping_method</code> explains exact, derived, inferred, overridden or unsupported decisions.</p></div><div><h3>Confidence</h3><p><code>model_confidence</code> is the model's self-reported overall output confidence. It is not a calibrated probability. Retrieval score, evidence strength and validator status are separate fields.</p></div></div><div className="docs-callout"><strong>Null semantics</strong><span><code>ABSTAINED</code> means evidence was assessed but insufficient. <code>NOT_APPLICABLE</code> means the field does not logically apply. <code>UNAVAILABLE</code> means historical metadata was not recorded.</span></div></section>
        <section id="docs-8" className="docs-section"><div className="docs-index">08 / OPERATIONS</div><h2>Runbook</h2><div className="docs-runbook"><div><b>Start backend</b><code>backend\\.venv\\Scripts\\python.exe -m uvicorn app.main:app --reload --port 8000</code></div><div><b>Start frontend</b><code>cd frontend; npm run dev</code></div><div><b>Open API contract</b><code>http://localhost:8000/docs</code></div><div><b>Open web app</b><code>http://localhost:5173/catalog</code></div><div><b>Run tests</b><code>cd backend; .\\.venv\\Scripts\\python.exe -m pytest -q</code></div></div><p className="docs-note">For production, move from local SQLite to PostgreSQL, put credentials in a secret manager, and run classification as a resumable worker rather than a browser request.</p></section>
        <section id="docs-9" className="docs-section"><div className="docs-index">09 / INTEGRATION RULES</div><h2>Rules for future contributors</h2><ol className="docs-rules"><li>Keep raw rule data immutable; a new revision is a new <code>SID + REV</code> record.</li><li>Keep parser, abstention and validation state canonical in the API.</li><li>Never mark AI proposals as human-reviewed.</li><li>Preserve provider, model, classifier version and run ID.</li><li>Never expose API keys, hidden prompts or chain-of-thought.</li><li>When adding a field, update schema, database model, serializer, API type and inspector together.</li></ol><div className="docs-final-links"><Link to="/catalog/rules">Browse rules →</Link><Link to="/models">Open Model Lab →</Link><Link to="/catalog/mitre">Explore MITRE →</Link></div></section>
      </main>
    </div>
  </div>;
}

