import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getFamily, type DetectionFamilyDetail } from "../services/api";
import { useI18n } from "../i18n";

export function FamilyDetail(){
  const { t, label, locale } = useI18n();
  const {slug=""}=useParams(); const [page,setPage]=useState(1); const limit=50;
  const [data,setData]=useState<DetectionFamilyDetail|null>(null); const [error,setError]=useState("");
  useEffect(()=>{void getFamily(slug,(page-1)*limit,limit).then(setData).catch(e=>setError(e instanceof Error?e.message:t("Family could not be loaded")));},[slug,page]);
  if(error)return <div className="error">{error}</div>; if(!data)return <div className="family-loading">{t("Preparing detection family…")}</div>;
  const f=data.family;
  return <div className="family-detail-page"><header className="family-detail-hero"><Link to="/catalog/families">← {t("Detection Families")}</Link><div className="section-kicker">{f.family_type} FAMILY · EXPLAINABLE GROUPING</div><h1>{f.name}</h1><p>{t("Inspect the detection surfaces, MITRE coverage and product decisions represented by this family.")}</p><div className="family-detail-actions"><Link className="primary" to={`/catalog/rules?family=${encodeURIComponent(f.slug)}`}>{t("Open in Rule Explorer →")}</Link><Link to={`/catalog?ask_family=${encodeURIComponent(f.name)}#catalog-assistant`}>{t("Ask Gemini about this family")}</Link></div></header>
    <section className="family-metric-strip"><div><b>{data.total}</b><span>{t("Rules")}</span></div><div><b>{f.protocols.length}</b><span>{t("Protocols")}</span></div><div><b>{f.mitre_count}</b><span>{t("MITRE techniques")}</span></div><div><b>{Object.values(data.provenance).reduce((a,b)=>a+b,0)}</b><span>{t("Evidence-backed links")}</span></div></section>
    <section className="family-profile-grid"><article className="panel"><div className="section-title"><span>01</span><h2>{t("Coverage profile")}</h2></div><Profile label={t("Protocols")} values={f.protocols}/><Profile label={t("Categories")} values={f.categories}/><Profile label="MITRE" values={f.mitre_ids}/><Profile label={t("Entity types")} values={f.entity_types}/></article><article className="panel"><div className="section-title"><span>02</span><h2>{t("Assignment provenance")}</h2></div><div className="family-provenance">{Object.entries(data.provenance).map(([key,value])=><div key={key}><span>{key.replaceAll("_"," ")}</span><b>{value}</b></div>)}</div><p className="family-help">{t("Provenance explains why each rule belongs here. Model similarity alone never creates a family.")}</p></article></section>
    <FamilyMitrePanel profile={data.mitre}/>
    <section className="panel family-rules"><div className="panel-heading"><div><div className="section-kicker">{t("UNDERLYING SIGNATURES")}</div><h2>{t("Detections in")} {f.name}</h2><p>{data.total} {t("rules")} · {t("page")} {data.page}/{data.total_pages}</p></div></div><div className="family-rule-list">{data.rules.map(rule=><div className="family-rule-entry" key={rule.id}><Link className="family-rule-main" to={`/rules/${rule.sid}${rule.classification?.id?`?classification_id=${rule.classification.id}`:""}`}><div><b>SID {rule.sid}</b><small>REV {rule.rev} · {rule.protocol.toUpperCase()} · {rule.source_file||t("source unknown")}</small><p>{rule.msg||t("No rule message")}</p><small className="family-rule-evidence">{t("Evidence")} · {evidenceSummary(rule.family_assignment.evidence)}</small></div><div className="family-rule-class"><span>{rule.classification?.category||t("Classification pending")}</span><small>{rule.classification?.mitre_technique_id||t("MITRE unassigned")}</small><em>{rule.family_assignment.provenance.replaceAll("_"," ")}</em></div></Link><Link className="family-rule-compare" to={`/catalog/compare?sids=${rule.sid}`}>{t("Compare")}</Link></div>)}</div><div className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>{t("← Previous")}</button><span>{t("Page")} {page} / {data.total_pages}</span><button disabled={page>=data.total_pages} onClick={()=>setPage(p=>p+1)}>{t("Next →")}</button></div></section>
  </div>;
}
function Profile({label,values}:{label:string;values:string[]}){const { t, label:translate } = useI18n();return <div className="family-profile-row"><b>{label}</b><div>{values.length?values.map(v=><span key={v}>{translate(v)}</span>):<em>{t("Not assigned")}</em>}</div></div>}
export function FamilyMitrePanel({profile}:{profile:DetectionFamilyDetail["mitre"]}){const { t, label } = useI18n();return <section className="panel family-mitre-panel"><div className="panel-heading"><div><div className="section-kicker">FAMILY → ATT&amp;CK</div><h2>MITRE ATT&amp;CK</h2><p>{profile.mapped_rule_count} {t("mapped")} · {profile.unmapped_rule_count} {t("unmapped family rules")}</p></div><Link className="mitre-all-families" to="/catalog/mitre">{t("Open MITRE Intelligence →")}</Link></div>{profile.techniques.length?<div className="family-mitre-techniques">{profile.techniques.map(item=><Link key={item.technique_id} to={`/catalog/mitre/${item.technique_id}`}><span>{item.technique_id}</span><strong>{item.name}</strong><small>{item.tactics.map(label).join(" · ")}</small><b>{item.rule_count} {t("rules")}</b></Link>)}</div>:<div className="empty">{t("This family has no canonical MITRE mapping.")}</div>}</section>}
function evidenceSummary(evidence:Record<string,unknown>){const value=evidence.value||evidence.matched_text||evidence.pattern||evidence.field;return typeof value==="string"?value:"Deterministic family evidence"}
