import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getMitreTechnique, getMitreTechniqueRules, translateTexts, type MitreTechnique, type MitreTechniqueDetail as Detail, type MitreTechniqueRules } from "../services/api";
import { useI18n } from "../i18n";

export function MitreTechniqueDetail(){
  const { t: translate, label, locale } = useI18n();
  const {techniqueId=""}=useParams(); const [page,setPage]=useState(1); const limit=50;
  const [detail,setDetail]=useState<Detail|null>(null); const [rules,setRules]=useState<MitreTechniqueRules|null>(null); const [error,setError]=useState(""); const [localizedDescription,setLocalizedDescription]=useState<string|null>(null);
  useEffect(()=>{setDetail(null);setPage(1);void getMitreTechnique(techniqueId).then(setDetail).catch(e=>setError(e instanceof Error?e.message:translate("Technique could not be loaded")));},[techniqueId]);
  useEffect(()=>{void getMitreTechniqueRules(techniqueId,(page-1)*limit,limit).then(setRules).catch(e=>setError(e instanceof Error?e.message:translate("Rules could not be loaded")));},[techniqueId,page]);
  useEffect(()=>{
    const source=detail?.technique.description||"";
    setLocalizedDescription(null);
    if(locale!=="tr"||!source)return;
    const cacheKey=`mitre-description-tr:${detail?.technique.technique_id}`;
    try{const cached=sessionStorage.getItem(cacheKey);if(cached){setLocalizedDescription(cached);return;}}catch{/* storage may be unavailable */}
    let active=true;
    void translateTexts([source],locale).then(result=>{
      if(!active)return;
      const translated=result.translations[0]||source;
      setLocalizedDescription(translated);
      try{sessionStorage.setItem(cacheKey,translated)}catch{/* storage may be unavailable */}
    }).catch(()=>{if(active)setLocalizedDescription(source)});
    return()=>{active=false};
  },[detail?.technique.description,detail?.technique.technique_id,locale]);
  if(error)return <div className="error page-error">{error} <Link to="/catalog/mitre">{translate("Back to MITRE catalogue")}</Link></div>;
  if(!detail||!rules)return <div className="family-loading">{translate("Preparing technique intelligence…")}</div>;
  const t=detail.technique; const description=locale==="tr"?(localizedDescription||translate("Translating ATT&CK description…")):t.description;
  return <div className="mitre-detail-page"><header className="mitre-detail-hero"><Link to="/catalog/mitre">← {translate("MITRE ATT&CK Intelligence")}</Link><div className="section-kicker">{translate(t.is_subtechnique?"SUB-TECHNIQUE":"TECHNIQUE")} · {translate("CATALOG COVERAGE")}</div><div className="mitre-title"><span>{t.technique_id}</span><h1>{label(t.name)}</h1></div><div className="mitre-tactic-chips">{t.tactics.map(value=><Link key={value} to={`/catalog/mitre?tactic=${encodeURIComponent(value)}`}>{label(value)}</Link>)}</div><p>{description||translate("Canonical ATT&CK description is not available in the local repository.")}</p></header>
    <section className="family-metric-strip mitre-detail-metrics"><div><b>{t.rule_count.toLocaleString(locale === "tr" ? "tr-TR" : "en-US")}</b><span>{translate("Catalog rules")}</span></div><div><b>{t.family_count}</b><span>{translate("Detection families")}</span></div><div><b>{detail.categories.length}</b><span>{translate("Categories")}</span></div><div><b>{detail.protocols.length}</b><span>{translate("Protocols")}</span></div></section>
    {t.rule_count===0&&<section className="panel coverage-gap-detail"><div className="section-title"><span>GAP</span><h2>{translate("Coverage gap assessment")}</h2></div><div className="gap-detail-grid"><div><b>{translate("Why this appears as a gap")}</b><p>{locale === "tr" ? `Kataloğun hiçbir kuralının en son başarılı sınıflandırması veya açık kaynak metadata'sı şu anda ${t.technique_id} ile eşleşmiyor. Bu bir katalog kanıtı boşluğudur; davranışın gözlemlenmesinin imkânsız olduğu anlamına gelmez.` : `No catalog rule’s latest successful classification or explicit source metadata currently maps to ${t.technique_id}. This is a catalog-evidence gap, not proof that the behavior is impossible to observe.`}</p></div><div><b>{translate("What is known")}</b><p>{description||translate("The local ATT&CK repository identifies this technique, but no canonical description is stored.")}</p></div><div><b>{translate("Recommended review")}</b><p>{translate("Inspect the parent and sub-techniques, confirm whether the behavior creates network-visible evidence, then search existing rules for the technique name and relevant protocol artifacts before authoring or sourcing new content.")}</p></div><div><b>{translate("Decision boundary")}</b><p>{translate("Do not claim coverage until a rule has explicit or validated inferred evidence. A neighboring technique or family association alone is not sufficient.")}</p></div></div><div className="gap-detail-actions"><Link to={`/catalog/rules?search=${encodeURIComponent(t.name)}`}>{locale === "tr" ? "Katalogda ara “" : "Search catalog for “"}{t.name} →</Link><Link to="/catalog/rule-packs">{translate("Open Rule Pack Builder →")}</Link></div></section>}
    <section className="mitre-detail-grid"><article className="panel mitre-relations"><div className="section-title"><span>01</span><h2>{translate("ATT&CK relationships")}</h2></div>{detail.parent&&<Relation label={translate("Parent technique")} item={detail.parent}/>}<div className="mitre-subtechniques"><b>{translate("Sub-techniques")}</b>{detail.subtechniques.length?detail.subtechniques.map(item=><Link key={item.technique_id} to={`/catalog/mitre/${item.technique_id}`}><span>{item.technique_id}</span><strong>{label(item.name)}</strong><small>{item.rule_count} {translate("catalog rules")}</small></Link>):<p>{translate("No canonical sub-techniques.")}</p>}</div></article>
      <article className="panel mitre-distribution"><div className="section-title"><span>02</span><h2>{translate("Catalog profile")}</h2></div><Distribution title={translate("Categories")} items={detail.categories}/><Distribution title={translate("Protocols")} items={detail.protocols}/><div className="mitre-product"><b>{translate("Product status")}</b>{Object.entries(detail.product_status).filter(([,count])=>count>0).map(([status,count])=><div key={status}><span>{label(status)}</span><strong>{count}</strong></div>)}</div></article>
    </section>
    <section className="panel mitre-family-panel"><div className="panel-heading"><div><div className="section-kicker">{translate("CROSS-NAVIGATION")}</div><h2>{translate("Related Detection Families")}</h2><p>{translate("Families are derived from the real rules carrying")} {t.technique_id}.</p></div><Link className="mitre-all-families" to={`/catalog/families?mitre_technique_id=${t.technique_id}`}>{translate("Browse filtered families →")}</Link></div><RelatedFamilyLinks families={detail.related_families}/></section>
    <section className="panel family-rules mitre-rule-panel"><div className="panel-heading"><div><div className="section-kicker">{translate("UNDERLYING SIGNATURES")}</div><h2>{translate("Rules mapped to")} {t.technique_id}</h2><p>{rules.total.toLocaleString(locale === "tr" ? "tr-TR" : "en-US")} {translate("rules")} · {translate("Page")} {rules.page}/{rules.total_pages}</p></div><Link className="mitre-all-families" to={`/catalog/rules?mitre_technique_id=${t.technique_id}`}>{translate("Open Rule Explorer →")}</Link></div><div className="family-rule-list">{rules.items.map(rule=><Link to={`/rules/${rule.sid}${rule.classification?.id?`?classification_id=${rule.classification.id}`:""}`} key={rule.id}><div><b>SID {rule.sid}</b><small>REV {rule.rev} · {rule.protocol.toUpperCase()} · {rule.source_file||translate("source unknown")}</small><p>{rule.msg||translate("No rule message")}</p><small className="family-rule-evidence">{translate("Mapping")} · {rule.mitre_mapping_sources.map(x=>x.replaceAll("_"," ")).join(" + ")}</small></div><div className="family-rule-class"><span>{rule.classification?.category||translate("Classification pending")}</span><small>{rule.family?.name||translate("Family unassigned")}</small><em>{translate("VIEW RULE ↗")}</em></div></Link>)}</div><div className="pagination"><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>{translate("← Previous")}</button><span>{translate("Page")} {rules.page} / {rules.total_pages}</span><button disabled={page>=rules.total_pages} onClick={()=>setPage(value=>value+1)}>{translate("Next →")}</button></div></section>
  </div>;
}

function Relation({label,item}:{label:string;item:MitreTechnique}){const { t, label: translateLabel } = useI18n();return <div className="mitre-relation"><b>{label}</b><Link to={`/catalog/mitre/${item.technique_id}`}><span>{item.technique_id}</span><strong>{translateLabel(item.name)}</strong><small>{item.rule_count} {t("catalog rules")}</small></Link></div>}
export function RelatedFamilyLinks({families}:{families:Detail["related_families"]}){const { t, label } = useI18n();return families.length?<div className="mitre-family-links">{families.map(family=><Link key={family.id} to={`/catalog/families/${family.slug}`}><span>{label(family.family_type)}</span><strong>{family.name}</strong><b>{family.rule_count} {t("rules")}</b></Link>)}</div>:<div className="empty">{t("No Detection Family is currently associated with mapped rules.")}</div>}
function Distribution({title,items}:{title:string;items:Array<{value:string;count:number}>}){const max=Math.max(1,...items.map(item=>item.count));const { label } = useI18n();return <div className="mitre-bars"><b>{title}</b>{items.slice(0,8).map(item=><div key={item.value}><span>{label(item.value)}</span><i><em style={{width:`${item.count/max*100}%`}}/></i><strong>{item.count}</strong></div>)}</div>}
