import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getMitreTechnique, getMitreTechniqueRules, type MitreTechnique, type MitreTechniqueDetail as Detail, type MitreTechniqueRules } from "../services/api";
import { useI18n } from "../i18n";

export function MitreTechniqueDetail(){
  const { t: translate, label, locale } = useI18n();
  const {techniqueId=""}=useParams(); const [page,setPage]=useState(1); const limit=50;
  const [detail,setDetail]=useState<Detail|null>(null); const [rules,setRules]=useState<MitreTechniqueRules|null>(null); const [error,setError]=useState("");
  useEffect(()=>{setDetail(null);setPage(1);void getMitreTechnique(techniqueId).then(setDetail).catch(e=>setError(e instanceof Error?e.message:"Technique could not be loaded"));},[techniqueId]);
  useEffect(()=>{void getMitreTechniqueRules(techniqueId,(page-1)*limit,limit).then(setRules).catch(e=>setError(e instanceof Error?e.message:"Rules could not be loaded"));},[techniqueId,page]);
  if(error)return <div className="error page-error">{error} <Link to="/catalog/mitre">{translate("Back to MITRE catalogue")}</Link></div>;
  if(!detail||!rules)return <div className="family-loading">{translate("Preparing technique intelligence…")}</div>;
  const t=detail.technique;
  return <div className="mitre-detail-page"><header className="mitre-detail-hero"><Link to="/catalog/mitre">← {translate("MITRE ATT&amp;CK Intelligence")}</Link><div className="section-kicker">{t.is_subtechnique?"SUB-TECHNIQUE":"TECHNIQUE"} · {translate("CATALOG COVERAGE")}</div><div className="mitre-title"><span>{t.technique_id}</span><h1>{label(t.name)}</h1></div><div className="mitre-tactic-chips">{t.tactics.map(value=><Link key={value} to={`/catalog/mitre?tactic=${encodeURIComponent(value)}`}>{label(value)}</Link>)}</div><p>{t.description||translate("Canonical ATT&CK description is not available in the local repository.")}</p></header>
    <section className="family-metric-strip mitre-detail-metrics"><div><b>{t.rule_count.toLocaleString(locale === "tr" ? "tr-TR" : "en-US")}</b><span>{translate("Catalog rules")}</span></div><div><b>{t.family_count}</b><span>{translate("Detection families")}</span></div><div><b>{detail.categories.length}</b><span>{translate("Categories")}</span></div><div><b>{detail.protocols.length}</b><span>{translate("Protocols")}</span></div></section>
    {t.rule_count===0&&<section className="panel coverage-gap-detail"><div className="section-title"><span>GAP</span><h2>{translate("Coverage gap assessment")}</h2></div><div className="gap-detail-grid"><div><b>{translate("Why this appears as a gap")}</b><p>{locale === "tr" ? `Kataloğun hiçbir kuralının en son başarılı sınıflandırması veya açık kaynak metadata'sı şu anda ${t.technique_id} ile eşleşmiyor. Bu bir katalog kanıtı boşluğudur; davranışın gözlemlenmesinin imkânsız olduğu anlamına gelmez.` : `No catalog rule’s latest successful classification or explicit source metadata currently maps to ${t.technique_id}. This is a catalog-evidence gap, not proof that the behavior is impossible to observe.`}</p></div><div><b>{translate("What is known")}</b><p>{t.description||translate("The local ATT&CK repository identifies this technique, but no canonical description is stored.")}</p></div><div><b>{translate("Recommended review")}</b><p>{translate("Inspect the parent and sub-techniques, confirm whether the behavior creates network-visible evidence, then search existing rules for the technique name and relevant protocol artifacts before authoring or sourcing new content.")}</p></div><div><b>{translate("Decision boundary")}</b><p>{translate("Do not claim coverage until a rule has explicit or validated inferred evidence. A neighboring technique or family association alone is not sufficient.")}</p></div></div><div className="gap-detail-actions"><Link to={`/catalog/rules?search=${encodeURIComponent(t.name)}`}>{locale === "tr" ? "Katalogda ara “" : "Search catalog for “"}{t.name} →</Link><Link to="/catalog/rule-packs">{translate("Open Rule Pack Builder →")}</Link></div></section>}
    <section className="mitre-detail-grid"><article className="panel mitre-relations"><div className="section-title"><span>01</span><h2>ATT&amp;CK relationships</h2></div>{detail.parent&&<Relation label="Parent technique" item={detail.parent}/>}<div className="mitre-subtechniques"><b>Sub-techniques</b>{detail.subtechniques.length?detail.subtechniques.map(item=><Link key={item.technique_id} to={`/catalog/mitre/${item.technique_id}`}><span>{item.technique_id}</span><strong>{item.name}</strong><small>{item.rule_count} catalog rules</small></Link>):<p>No canonical sub-techniques.</p>}</div></article>
      <article className="panel mitre-distribution"><div className="section-title"><span>02</span><h2>Catalog profile</h2></div><Distribution title="Categories" items={detail.categories}/><Distribution title="Protocols" items={detail.protocols}/><div className="mitre-product"><b>Product status</b>{Object.entries(detail.product_status).filter(([,count])=>count>0).map(([status,count])=><div key={status}><span>{status.replaceAll("_"," ")}</span><strong>{count}</strong></div>)}</div></article>
    </section>
    <section className="panel mitre-family-panel"><div className="panel-heading"><div><div className="section-kicker">CROSS-NAVIGATION</div><h2>Related Detection Families</h2><p>Families are derived from the real rules carrying {t.technique_id}.</p></div><Link className="mitre-all-families" to={`/catalog/families?mitre_technique_id=${t.technique_id}`}>Browse filtered families →</Link></div><RelatedFamilyLinks families={detail.related_families}/></section>
    <section className="panel family-rules mitre-rule-panel"><div className="panel-heading"><div><div className="section-kicker">UNDERLYING SIGNATURES</div><h2>Rules mapped to {t.technique_id}</h2><p>{rules.total.toLocaleString("tr-TR")} rules · page {rules.page}/{rules.total_pages}</p></div><Link className="mitre-all-families" to={`/catalog/rules?mitre_technique_id=${t.technique_id}`}>Open Rule Explorer →</Link></div><div className="family-rule-list">{rules.items.map(rule=><Link to={`/rules/${rule.sid}${rule.classification?.id?`?classification_id=${rule.classification.id}`:""}`} key={rule.id}><div><b>SID {rule.sid}</b><small>REV {rule.rev} · {rule.protocol.toUpperCase()} · {rule.source_file||"source unknown"}</small><p>{rule.msg||"No rule message"}</p><small className="family-rule-evidence">Mapping · {rule.mitre_mapping_sources.map(x=>x.replaceAll("_"," ")).join(" + ")}</small></div><div className="family-rule-class"><span>{rule.classification?.category||"Classification pending"}</span><small>{rule.family?.name||"Family unassigned"}</small><em>VIEW RULE ↗</em></div></Link>)}</div><div className="pagination"><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>← Previous</button><span>Page {rules.page} / {rules.total_pages}</span><button disabled={page>=rules.total_pages} onClick={()=>setPage(value=>value+1)}>Next →</button></div></section>
  </div>;
}

function Relation({label,item}:{label:string;item:MitreTechnique}){return <div className="mitre-relation"><b>{label}</b><Link to={`/catalog/mitre/${item.technique_id}`}><span>{item.technique_id}</span><strong>{item.name}</strong><small>{item.rule_count} catalog rules</small></Link></div>}
export function RelatedFamilyLinks({families}:{families:Detail["related_families"]}){return families.length?<div className="mitre-family-links">{families.map(family=><Link key={family.id} to={`/catalog/families/${family.slug}`}><span>{family.family_type}</span><strong>{family.name}</strong><b>{family.rule_count} rules</b></Link>)}</div>:<div className="empty">No Detection Family is currently associated with mapped rules.</div>}
function Distribution({title,items}:{title:string;items:Array<{value:string;count:number}>}){const max=Math.max(1,...items.map(item=>item.count));return <div className="mitre-bars"><b>{title}</b>{items.slice(0,8).map(item=><div key={item.value}><span>{item.value}</span><i><em style={{width:`${item.count/max*100}%`}}/></i><strong>{item.count}</strong></div>)}</div>}
