import { useEffect, useState } from "react";
import { DecisionAssessment } from "../components/DecisionAssessment";
import { Link } from "react-router-dom";
import { compareModels, getModelConfig, getRules, saveComparisonReview, testModel, updateModelConfig } from "../services/api";

const fields = [["detected_behavior","Behavior"],["detected_entity","Entity"],["entity_type","Entity Type"],["category","Category"],["subcategory","Subcategory"],["mitre_tactic","MITRE Tactic"],["mitre_technique","MITRE Technique"],["mitre_technique_id","MITRE ID"],["cyber_kill_chain_phase","Kill Chain"]] as const;
function val(c:any, key:string) { if (!c) return "—"; if (key === "validation") return c.validation?.status || "UNAVAILABLE"; return c[key] || "Not assigned"; }
export function ModelLab() {
  const [config,setConfig]=useState<any>(null); const [form,setForm]=useState<any>({}); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState("");
  const [rule,setRule]=useState<any>(null); const [search,setSearch]=useState(""); const [comparison,setComparison]=useState<any>(null); const [preference,setPreference]=useState("UNSURE"); const [note,setNote]=useState("");
  useEffect(()=>{void getModelConfig().then(x=>{setConfig(x);setForm({gemini_model:x.gemini.model,ollama_base_url:x.ollama.base_url,ollama_model:x.ollama.model,ai_provider:x.default_provider})})},[]);
  const save=async()=>{setBusy("save");try{const x=await updateModelConfig(form);setConfig(x);setNotice("Configuration saved. Secrets remain backend-only.")}catch(e){setNotice(e instanceof Error?e.message:"Save failed")}finally{setBusy("")}};
  const test=async(p:"gemini"|"ollama")=>{setBusy(p);try{const x=await testModel(p);setNotice(x.ok?`${p} connected · ${x.model} · ${x.latency_ms} ms`:x.error)}catch(e){setNotice(e instanceof Error?e.message:"Test failed")}finally{setBusy("")}};
  const refreshWorkspace=async()=>{setBusy("refresh");try{await getModelConfig();window.location.reload()}catch(e){setNotice(e instanceof Error?e.message:"Backend refresh failed");setBusy("")}};
  const findRule=async()=>{if(!search)return;try{const x=await getRules(new URLSearchParams({search,limit:"1"}));setRule(x.items[0]||null);setComparison(null)}catch(e){setNotice(e instanceof Error?e.message:"Rule search failed")}};
  const run=async()=>{if(!rule)return;setBusy("compare");try{setComparison(await compareModels({sid:rule.sid,rev:rule.rev,models:["gemini","ollama"]}))}catch(e){setNotice(e instanceof Error?e.message:"Comparison failed")}finally{setBusy("")}};
  if(!config)return <div className="loading">Loading Model Lab…</div>;
  const results:any[] = comparison?.results || [];
  // Provider values in historical classifications were stored as both
  // lowercase (new pipeline) and uppercase (legacy imports). Normalize the
  // comparison lookup so a valid Gemini result can never disappear from the
  // side-by-side view because of casing.
  const providerName = (item:any) => String(item?.provider || "").toLowerCase();
  const gem=results.find(x=>providerName(x).includes("gemini"));
  const qwen=results.find(x=>providerName(x).includes("ollama"));
  const differs=(key:string)=>gem&&qwen&&key!=="detected_behavior"&&String(val(gem,key))!==String(val(qwen,key));
  return <><header className="topbar"><div><Link className="back" to="/">← Rule Explorer</Link><div className="brand-line"><span className="eyebrow">MODEL OPERATIONS</span></div><h1>Model Control Center</h1><p>Configure providers, test local inference, and compare classification outputs.</p></div><div className="topbar-actions"><div className="live-status"><i/> Classifier {config.classifier_version}</div><button onClick={()=>void refreshWorkspace()} disabled={!!busy}>{busy==="refresh"?"Refreshing…":"Refresh services"}</button></div></header>{notice&&<div className="error">{notice}</div>}
    <section className="model-cards"><article className="panel model-card"><div className="section-title"><span>GEMINI</span><h2>Gemini API</h2><span className="badge auto_classified">{config.gemini.api_key_configured?"Configured":"Not configured"}</span></div><div className="model-form"><label>API Key<input type="password" placeholder={config.gemini.api_key_configured?"••••••••••••••••":"Paste key (never displayed)"} value={form.gemini_api_key||""} onChange={e=>setForm({...form,gemini_api_key:e.target.value})}/></label><label>Model<input value={form.gemini_model||""} onChange={e=>setForm({...form,gemini_model:e.target.value})}/></label><p>Inference mode: API</p><div className="review-actions"><button className="primary" onClick={save} disabled={!!busy}>{busy==="save"?"Saving…":"Save Configuration"}</button><button onClick={()=>void test("gemini")} disabled={!!busy}>{busy==="gemini"?"Testing…":"Test Connection"}</button></div></div></article>
    <article className="panel model-card"><div className="section-title"><span>OLLAMA</span><h2>Local Qwen</h2><span className="badge neutral">LOCAL</span></div><div className="model-form"><label>Base URL<input value={form.ollama_base_url||""} onChange={e=>setForm({...form,ollama_base_url:e.target.value})}/></label><label>Model<input value={form.ollama_model||""} onChange={e=>setForm({...form,ollama_model:e.target.value})}/></label><p>Configured model: <span className="mono">{config.ollama.model}</span>. Start with <code>ollama serve</code>; pull with <code>ollama pull qwen3:8b</code>.</p><div className="review-actions"><button className="primary" onClick={save} disabled={!!busy}>{busy==="save"?"Saving…":"Save Configuration"}</button><button onClick={()=>void test("ollama")} disabled={!!busy}>{busy==="ollama"?"Testing…":"Test Local Model"}</button></div></div></article></section><section className="panel default-provider"><div className="model-form"><label>Default Classification Provider<select value={form.ai_provider||config.default_provider} onChange={e=>setForm({...form,ai_provider:e.target.value})}><option value="gemini">Gemini API</option><option value="ollama">Qwen3 8B · Local</option></select></label><p>Only future classifications use this default; historical results remain immutable.</p></div></section>
    <section className="panel comparison-lab"><div className="panel-heading"><div><div className="section-kicker">ONE RULE · TWO MODELS</div><h2>Model Comparison Lab</h2><p>Agreement is not accuracy; audited expected labels are shown only when available.</p></div></div><div className="model-form rule-picker"><label>Search SID or message<input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void findRule()} placeholder="2060513 or AnyDesk…"/></label><button onClick={()=>void findRule()}>Find Rule</button></div>{rule&&<><div className="rule-meta"><span>SID {rule.sid}</span><span>REV {rule.rev}</span><span>{rule.msg||"No message"}</span></div><pre className="raw-rule">{rule.raw_rule}</pre><button className="primary run-compare" onClick={()=>void run()} disabled={!!busy}>{busy==="compare"?"Running both models…":"Run Comparison"}</button></>}{comparison&&<div className="comparison-grid">{[["Gemini · API",gem],["Qwen3 8B · LOCAL",qwen]].map(([title,c])=><article className="panel result-card" key={title as string}><div className="section-title"><span>{title as string}</span><span className={`badge ${c?.classification_status==="FAILED"?"failed":"auto_classified"}`}>{c?c.classification_status:"FAILED"}</span></div>{c?<><DecisionAssessment classification={c}/><div className="classification-grid">{fields.map(([key,label])=><label key={key}>{label}<div className="value">{val(c,key)}{c.field_decisions?.[key]?.status&&c.field_decisions[key].status!=="ASSIGNED"&&<small>{c.field_decisions[key].status}</small>}</div></label>)}</div></>:<div className="empty">Provider result unavailable.</div>}</article>)}</div>}{comparison&&gem&&qwen&&<div className="comparison-review"><strong>Which result is better?</strong><select value={preference} onChange={e=>setPreference(e.target.value)}><option value="UNSURE">Unsure</option><option value="GEMINI">Gemini</option><option value="QWEN">Qwen</option><option value="BOTH_ACCEPTABLE">Both acceptable</option><option value="NEITHER">Neither</option></select><input placeholder="Optional comparison note" value={note} onChange={e=>setNote(e.target.value)}/><button onClick={()=>void saveComparisonReview(rule.sid,{classification_a_id:gem.id,classification_b_id:qwen.id,preference,note})}>Save Comparison Review</button></div>}</section>
  </>;
}
