import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { getRule } from "../services/api";
import { addRuleToPack, createRulePack, deleteRulePack, getActiveRulePackId, loadRulePacks, removeRuleFromPack, setActiveRulePack, updateRulePack, type StoredRulePack } from "../services/rulePack";
import type { Rule } from "../types";
import { useI18n } from "../i18n";
function download(name:string,content:string,type="text/plain"){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
export function RulePackBuilder(){
 const { t, label } = useI18n();
 const [packs,setPacks]=useState<StoredRulePack[]>([]),[activeId,setActiveId]=useState(""),[newName,setNewName]=useState(""),[sid,setSid]=useState(""),[rules,setRules]=useState<Rule[]>([]),[error,setError]=useState("");
 const refresh=()=>{const p=loadRulePacks();setPacks(p);setActiveId(current=>p.some(x=>x.id===current)?current:(getActiveRulePackId()||p[0]?.id||""))};
 useEffect(()=>{refresh();window.addEventListener("rule-pack-change",refresh);return()=>window.removeEventListener("rule-pack-change",refresh)},[]);
 const active=packs.find(p=>p.id===activeId)||null;
 useEffect(()=>{if(!active){setRules([]);return}setActiveRulePack(active.id);void Promise.all(active.sids.map(x=>getRule(String(x)))).then(setRules).catch(e=>setError(e instanceof Error?e.message:t("Pack rules could not be loaded")))},[activeId,active?.updatedAt]);
 const create=()=>{if(!newName.trim())return;const p=createRulePack(newName);setNewName("");setActiveId(p.id)};
 const removePack=()=>{if(!active)return;if(!window.confirm(`${t("Delete rule pack")} “${active.name}”?`))return;deleteRulePack(active.id);setActiveId("")};
 const add=()=>{const value=Number(sid);if(!active||!Number.isSafeInteger(value)){setError(t("Choose a pack and enter a valid SID."));return}addRuleToPack(active.id,value);setSid("")};
 const remove=(value:number)=>{if(active)removeRuleFromPack(active.id,value)};
 const mapped=useMemo(()=>rules.filter(x=>x.classification?.mitre_technique_id),[rules]),techniques=[...new Set(mapped.map(x=>x.classification!.mitre_technique_id!))],name=(active?.name||"rule-pack").replace(/[^a-zA-Z0-9-_]/g,"-");
 const manifest=()=>({format_version:"suricata-rule-pack-v1",name:active?.name,generated_at:new Date().toISOString(),rule_count:rules.length,sids:rules.map(x=>({sid:x.sid,rev:x.rev,source_file:x.source_file,families:x.families||[],classification:{category:x.classification?.category||null,mitre_technique_id:x.classification?.mitre_technique_id||null}}))});
 return <div className="product-intelligence-page"><header className="intelligence-hero"><div className="section-kicker">{t("RULE PACK BUILDER")}</div><h1>{t("Build and manage multiple rule packs.")}</h1><p>{t("Keep separate packs for different products, environments or deployment decisions, then export the currently selected pack.")}</p></header><section className="pack-layout"><aside className="panel pack-summary"><div className="section-title"><span>01</span><h2>{t("Your rule packs")}</h2></div><div className="pack-tabs">{packs.map(p=><button className={p.id===activeId?"active":""} onClick={()=>setActiveId(p.id)} key={p.id}><b>{p.name}</b><span>{p.sids.length} {t("rules")}</span></button>)}</div><div className="pack-add"><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder={t("New pack name")}/><button onClick={create}>{t("Create pack")}</button></div>{active&&<><label>{t("Selected pack name")}<input value={active.name} onChange={e=>updateRulePack(active.id,{name:e.target.value})}/></label><button className="pack-delete" onClick={removePack}>{t("Delete this pack")}</button><div className="pack-add"><input value={sid} onChange={e=>setSid(e.target.value)} placeholder={t("Add SID")}/><button onClick={add}>{t("Add")}</button></div><dl><Row name={t("Rules")} value={rules.length}/><Row name={t("Mapped rules")} value={mapped.length}/><Row name={t("Techniques")} value={techniques.length}/></dl><div className="pack-exports"><button className="primary" disabled={!rules.length} onClick={()=>download(`${name}.rules`,rules.map(x=>x.raw_rule).join("\n")+"\n")}>{t("Download .rules")}</button><button disabled={!rules.length} onClick={()=>download(`${name}-manifest.json`,JSON.stringify(manifest(),null,2)+"\n","application/json")}>{t("Download manifest")}</button></div></>}</aside><article className="panel pack-rules"><div className="section-title"><span>02</span><h2>{active?.name||t("Select or create a pack")}</h2><strong>{rules.length}</strong></div>{error&&<div className="error">{error}</div>}{rules.length?rules.map(rule=><div className="pack-rule" key={rule.sid}><div><Link to={`/rules/${rule.sid}`}>SID {rule.sid} / {rule.rev}</Link><strong>{rule.msg||t("Untitled rule")}</strong><small>{rule.classification?.category||t("Unclassified")} · {rule.classification?.mitre_technique_id||t("MITRE unmapped")}</small></div><div><Link to={`/catalog/compare?sids=${rules.slice(0,3).map(x=>x.sid).concat(rule.sid).filter((x,i,a)=>a.indexOf(x)===i).slice(0,4).join(",")}`}>{t("Compare")}</Link><button onClick={()=>remove(rule.sid)}>{t("Remove")}</button></div></div>):<div className="family-empty"><b>{t("No rules in this pack.")}</b><span>{t("Use “Add to Rule Pack” on any rule row, or enter a SID here.")}</span></div>}</article></section></div>
}
function Row({name,value}:{name:string;value:number}){return <div><dt>{name}</dt><dd>{value.toLocaleString()}</dd></div>}
